# Welcome to Jekyll!
title: Tarrex
url: https://tarrex.com
description: >
  Tarrex's homepage.

# Outputting
permalink:  /:title
timezone:   Asia/Shanghai

# Custom
color:
  theme: '#00ADB5 !default'
  text: '#333333 !default'
  background: '#fdfdfd !default'

date_format: '%Y-%m-%d'

analytics:
  google: UA-54701139-1
  cloudflare: 4edcbe7acd4d459d8509c7e5bc071b53
